code --install-extension akamud.vscode-theme-onedark
code --install-extension akamud.vscode-theme-onelight
code --install-extension esbenp.prettier-vscode
code --install-extension Gruntfuggly.todo-tree
code --install-extension kisstkondoros.vscode-gutter-preview
code --install-extension kortina.vscode-markdown-notes
code --install-extension PKief.material-icon-theme
code --install-extension skn0tt.markdown-link-expander
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-ukrainian
code --install-extension vscodevim.vim
code --install-extension WakaTime.vscode-wakatime
code --install-extension yzhang.markdown-all-in-one