source "$HOME/.config/dotfiles/shell/exports.zsh"
source "$HOME/.config/dotfiles/shell/plugins.zsh"
source "$HOME/.config/dotfiles/shell/aliases.zsh"
source "$HOME/.config/dotfiles/shell/functions.zsh"
source "$HOME/.config/dotfiles/shell/fzf.zsh"
