source "$HOME/.dotfiles/zsh/exports.zsh"
source "$HOME/.dotfiles/zsh/plugins.zsh"
source "$HOME/.dotfiles/zsh/aliases.zsh"
source "$HOME/.dotfiles/zsh/functions.zsh"
source "$HOME/.dotfiles/zsh/fzf.zsh"
source "$HOME/.dotfiles/zsh/.sensitive"
